---
- name: Setting up an instrafracture
  hosts: aws_ec2
  gather_facts: yes
  become: true
  vars:
    ansible_ssh_private_key_file: "/home/ec2-user/.ssh/dolev.pem"
  roles:
    - role_destroy_infra